name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: g++ -Wall -Wextra -o testchecker *.c*
      
    - name: run
      run: ./testchecker
